

CREATE TABLE "ComponentClass" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"equivalentClasses" TEXT, 
	part_number TEXT, 
	part_type TEXT, 
	part_name TEXT, 
	part_display_name TEXT, 
	"subClassOf" TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE "Loinc" (
	codes TEXT, 
	parts TEXT, 
	PRIMARY KEY (codes, parts)
);

CREATE TABLE "MethodClass" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"equivalentClasses" TEXT, 
	part_number TEXT, 
	part_type TEXT, 
	part_name TEXT, 
	part_display_name TEXT, 
	"subClassOf" TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE "PartClass" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"equivalentClasses" TEXT, 
	"subClassOf" TEXT, 
	part_number TEXT, 
	part_type TEXT, 
	part_name TEXT, 
	part_display_name TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE "PropertyClass" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"equivalentClasses" TEXT, 
	part_number TEXT, 
	part_type TEXT, 
	part_name TEXT, 
	part_display_name TEXT, 
	"subClassOf" TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE "ScaleClass" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"equivalentClasses" TEXT, 
	part_number TEXT, 
	part_type TEXT, 
	part_name TEXT, 
	part_display_name TEXT, 
	"subClassOf" TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE "SystemClass" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"equivalentClasses" TEXT, 
	part_number TEXT, 
	part_type TEXT, 
	part_name TEXT, 
	part_display_name TEXT, 
	"subClassOf" TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE "Thing" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"subClassOf" TEXT, 
	"equivalentClasses" TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE "TimeClass" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"equivalentClasses" TEXT, 
	part_number TEXT, 
	part_type TEXT, 
	part_name TEXT, 
	part_display_name TEXT, 
	"subClassOf" TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE "LoincCodeClass" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"subClassOf" TEXT, 
	"equivalentClasses" TEXT, 
	loinc_number TEXT, 
	long_common_name TEXT, 
	formal_name TEXT, 
	short_name TEXT, 
	status TEXT, 
	loinc_class TEXT, 
	loinc_class_type TEXT, 
	has_component TEXT, 
	has_property TEXT, 
	has_time TEXT, 
	has_system TEXT, 
	has_scale TEXT, 
	has_method TEXT, 
	has_component_analyte TEXT, 
	has_component_challenge TEXT, 
	has_component_count TEXT, 
	has_component_adjustment TEXT, 
	has_time_core TEXT, 
	has_time_modifier TEXT, 
	has_system_core TEXT, 
	has_system_super_system TEXT, 
	semantic_analyte_gene TEXT, 
	syntax_analyte_core TEXT, 
	syntax_analyte_suffix TEXT, 
	syntax_analyte_divisor TEXT, 
	syntax_analyte_divisor_suffix TEXT, 
	syntax_analyte_numerator TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(has_component) REFERENCES "ComponentClass" (id), 
	FOREIGN KEY(has_property) REFERENCES "PropertyClass" (id), 
	FOREIGN KEY(has_time) REFERENCES "TimeClass" (id), 
	FOREIGN KEY(has_system) REFERENCES "SystemClass" (id), 
	FOREIGN KEY(has_scale) REFERENCES "ScaleClass" (id), 
	FOREIGN KEY(has_method) REFERENCES "MethodClass" (id), 
	FOREIGN KEY(has_component_analyte) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_component_challenge) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_component_count) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_component_adjustment) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_time_core) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_time_modifier) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_system_core) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_system_super_system) REFERENCES "PartClass" (id), 
	FOREIGN KEY(semantic_analyte_gene) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_core) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_suffix) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_divisor) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_divisor_suffix) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_numerator) REFERENCES "PartClass" (id)
);

CREATE TABLE "LoincCodeClassIntersection" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"subClassOf" TEXT, 
	"equivalentClasses" TEXT, 
	loinc_number TEXT, 
	long_common_name TEXT, 
	formal_name TEXT, 
	short_name TEXT, 
	status TEXT, 
	loinc_class TEXT, 
	loinc_class_type TEXT, 
	has_component TEXT, 
	has_property TEXT, 
	has_time TEXT, 
	has_system TEXT, 
	has_scale TEXT, 
	has_method TEXT, 
	has_component_analyte TEXT, 
	has_component_challenge TEXT, 
	has_component_count TEXT, 
	has_component_adjustment TEXT, 
	has_time_core TEXT, 
	has_time_modifier TEXT, 
	has_system_core TEXT, 
	has_system_super_system TEXT, 
	semantic_analyte_gene TEXT, 
	syntax_analyte_core TEXT, 
	syntax_analyte_suffix TEXT, 
	syntax_analyte_divisor TEXT, 
	syntax_analyte_divisor_suffix TEXT, 
	syntax_analyte_numerator TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(has_component) REFERENCES "ComponentClass" (id), 
	FOREIGN KEY(has_property) REFERENCES "PropertyClass" (id), 
	FOREIGN KEY(has_time) REFERENCES "TimeClass" (id), 
	FOREIGN KEY(has_system) REFERENCES "SystemClass" (id), 
	FOREIGN KEY(has_scale) REFERENCES "ScaleClass" (id), 
	FOREIGN KEY(has_method) REFERENCES "MethodClass" (id), 
	FOREIGN KEY(has_component_analyte) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_component_challenge) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_component_count) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_component_adjustment) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_time_core) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_time_modifier) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_system_core) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_system_super_system) REFERENCES "PartClass" (id), 
	FOREIGN KEY(semantic_analyte_gene) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_core) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_suffix) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_divisor) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_divisor_suffix) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_numerator) REFERENCES "PartClass" (id)
);

CREATE TABLE "LoincCodeClassNonIntersection" (
	id TEXT NOT NULL, 
	label TEXT, 
	description TEXT, 
	"subClassOf" TEXT, 
	"equivalentClasses" TEXT, 
	loinc_number TEXT, 
	long_common_name TEXT, 
	formal_name TEXT, 
	short_name TEXT, 
	status TEXT, 
	loinc_class TEXT, 
	loinc_class_type TEXT, 
	has_component TEXT, 
	has_property TEXT, 
	has_time TEXT, 
	has_system TEXT, 
	has_scale TEXT, 
	has_method TEXT, 
	has_component_analyte TEXT, 
	has_component_challenge TEXT, 
	has_component_count TEXT, 
	has_component_adjustment TEXT, 
	has_time_core TEXT, 
	has_time_modifier TEXT, 
	has_system_core TEXT, 
	has_system_super_system TEXT, 
	semantic_analyte_gene TEXT, 
	syntax_analyte_core TEXT, 
	syntax_analyte_suffix TEXT, 
	syntax_analyte_divisor TEXT, 
	syntax_analyte_divisor_suffix TEXT, 
	syntax_analyte_numerator TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(has_component) REFERENCES "ComponentClass" (id), 
	FOREIGN KEY(has_property) REFERENCES "PropertyClass" (id), 
	FOREIGN KEY(has_time) REFERENCES "TimeClass" (id), 
	FOREIGN KEY(has_system) REFERENCES "SystemClass" (id), 
	FOREIGN KEY(has_scale) REFERENCES "ScaleClass" (id), 
	FOREIGN KEY(has_method) REFERENCES "MethodClass" (id), 
	FOREIGN KEY(has_component_analyte) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_component_challenge) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_component_count) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_component_adjustment) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_time_core) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_time_modifier) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_system_core) REFERENCES "PartClass" (id), 
	FOREIGN KEY(has_system_super_system) REFERENCES "PartClass" (id), 
	FOREIGN KEY(semantic_analyte_gene) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_core) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_suffix) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_divisor) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_divisor_suffix) REFERENCES "PartClass" (id), 
	FOREIGN KEY(syntax_analyte_numerator) REFERENCES "PartClass" (id)
);
