PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE {
  ?s ?p ?o .
}
WHERE {
# Ideally remove dynamically
#   # Remove the jellyfish sting class itself and all its descendants
#   {
#     # Direct class
#     BIND(<http://snomed.info/id/274920002> AS ?s)
#     ?s ?p ?o .
#   }
#   UNION
#   {
#     # All descendants (subclasses at any level)
#     ?s rdfs:subClassOf* <http://snomed.info/id/274920002> .
#     ?s ?p ?o .
#   }
#   UNION
#   {
#     # Any axioms where these classes appear as objects
#     ?s ?p ?o .
#     FILTER(?o IN (<http://snomed.info/id/274920002>) ||
#            EXISTS { ?o rdfs:subClassOf* <http://snomed.info/id/274920002> })
#   }

# Simple implementation: we know that it only has these shallow descendants
  
  # Remove the main jellyfish sting class
  {
    BIND(<http://snomed.info/id/274920002> AS ?s)
    ?s ?p ?o .
  }
  UNION
  # Remove the specific subclasses
  {
    ?s ?p ?o .
    FILTER(?s IN (
      <http://snomed.info/id/217688004>,
      <http://snomed.info/id/242603009>,
      <http://snomed.info/id/1252768006>,
      <http://snomed.info/id/269707006>
    ))
  }
  UNION
  # Remove subclass axioms connecting these classes to the parent
  {
    ?s rdfs:subClassOf <http://snomed.info/id/274920002> .
    ?s ?p ?o .
    FILTER(?s IN (
      <http://snomed.info/id/217688004>,
      <http://snomed.info/id/242603009>,
      <http://snomed.info/id/1252768006>,
      <http://snomed.info/id/269707006>
    ))
  }
}