

###
GET {{fhir-api}}/metadata
Authorization: Basic {{loinc-username}} {{loinc-password}}

>> response/metadata.json

###
GET {{fhir-api}}/ConceptMap?_summary=true
Accept: application/fhir+json
Authorization: Basic {{loinc-username}} {{loinc-password}}

>>! response/ConceptMap-summary.json



### Translate to NCBI gene
GET {{fhir-api}}/ConceptMap/httpswwwncbinlmnihgovgene-2.72/$translate?code=LP101031-5
Accept: application/fhir+json
Authorization: Basic {{loinc-username}} {{loinc-password}}

### Translate to HGNC gene
GET {{fhir-api}}/ConceptMap/httpwwwgenenamesorg-2.72/$translate?code=LP101031-5
Accept: application/fhir+json
Authorization: Basic {{loinc-username}} {{loinc-password}}


########################################


###
GET {{fhir-api}}/ConceptMap/httpswwwncbinlmnihgovgene-2.70
Accept: application/fhir+json
Authorization: Basic {{loinc-username}} {{loinc-password}}

>>! response/ConceptMap-gene-ncbi-2.70.json

###
GET {{fhir-api}}/ConceptMap/httpswwwncbinlmnihgovgene-2.71
Accept: application/fhir+json
Authorization: Basic {{loinc-username}} {{loinc-password}}

>>! response/ConceptMap-gene-ncbi-2.71.json


###
GET {{fhir-api}}/ConceptMap/httpswwwncbinlmnihgovgene-2.72
Accept: application/fhir+json
Authorization: Basic {{loinc-username}} {{loinc-password}}

>>! response/ConceptMap-gene-ncbi-2.72.json

#######################################################

###
GET {{fhir-api}}/ConceptMap/httpwwwgenenamesorg-2.70
Accept: application/fhir+json
Authorization: Basic {{loinc-username}} {{loinc-password}}

>>! response/ConceptMap-gene-genename-2.70.json

###
GET {{fhir-api}}/ConceptMap/httpwwwgenenamesorg-2.71
Accept: application/fhir+json
Authorization: Basic {{loinc-username}} {{loinc-password}}

>>! response/ConceptMap-gene-genename-2.71.json

###
GET {{fhir-api}}/ConceptMap/httpwwwgenenamesorg-2.72
Accept: application/fhir+json
Authorization: Basic {{loinc-username}} {{loinc-password}}

>>! response/ConceptMap-gene-genename-2.72.json
