# Check class equivalence
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?class ?equivClass
WHERE {
  ?class a owl:Class .
    OPTIONAL {?class owl:equivalentClass ?equivClass .}
}

