# Get top level branch classes
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?class ?label
WHERE {
  ?class a owl:Class .
  OPTIONAL { ?class rdfs:label ?label }
  FILTER NOT EXISTS { ?class rdfs:subClassOf ?super .
                      FILTER(?super != owl:Thing && ?super != ?class) }
}
